In [1]:
import numpy as np
import pandas as pd

In [2]:
car_data = pd.read_csv("Car details v3.csv")
car_data.head(10)

name  year  selling_price  km_driven  \
0                Maruti Swift Dzire VDI  2014         450000     145500   
1          Skoda Rapid 1.5 TDI Ambition  2014         370000     120000   
2              Honda City 2017-2020 EXi  2006         158000     140000   
3             Hyundai i20 Sportz Diesel  2010         225000     127000   
4                Maruti Swift VXI BSIII  2007         130000     120000   
5         Hyundai Xcent 1.2 VTVT E Plus  2017         440000      45000   
6          Maruti Wagon R LXI DUO BSIII  2007          96000     175000   
7                    Maruti 800 DX BSII  2001          45000       5000   
8                      Toyota Etios VXD  2011         350000      90000   
9  Ford Figo Diesel Celebration Edition  2013         200000     169000   

     fuel seller_type transmission         owner     mileage   engine  \
0  Diesel  Individual       Manual   First Owner   23.4 kmpl  1248 CC   
1  Diesel  Individual       Manual  Second Owner  21.14 kmpl  1498 CC   
2  Petrol  Individual       Manual   Third Owner   17.7 kmpl  1497 CC   
3  Diesel  Individual       Manual   First Owner   23.0 kmpl  1396 CC   
4  Petrol  Individual       Manual   First Owner   16.1 kmpl  1298 CC   
5  Petrol  Individual       Manual   First Owner  20.14 kmpl  1197 CC   
6     LPG  Individual       Manual   First Owner  17.3 km/kg  1061 CC   
7  Petrol  Individual       Manual  Second Owner   16.1 kmpl   796 CC   
8  Diesel  Individual       Manual   First Owner  23.59 kmpl  1364 CC   
9  Diesel  Individual       Manual   First Owner   20.0 kmpl  1399 CC   

    max_power                    torque  seats  
0      74 bhp            190Nm@ 2000rpm    5.0  
1  103.52 bhp       250Nm@ 1500-2500rpm    5.0  
2      78 bhp     12.7@ 2,700(kgm@ rpm)    5.0  
3      90 bhp  22.4 kgm at 1750-2750rpm    5.0  
4    88.2 bhp     11.5@ 4,500(kgm@ rpm)    5.0  
5   81.86 bhp         113.75nm@ 4000rpm    5.0  
6    57.5 bhp      7.8@ 4,500(kgm@ rpm)    5.0  
7      37 bhp             59Nm@ 2500rpm    4.0  
8    67.1 bhp       170Nm@ 1800-2400rpm    5.0  
9    68.1 bhp            160Nm@ 2000rpm    5.0

In [3]:
car_data["name"].unique()

array(['Maruti Swift Dzire VDI', 'Skoda Rapid 1.5 TDI Ambition',
       'Honda City 2017-2020 EXi', ..., 'Tata Nexon 1.5 Revotorq XT',
       'Ford Freestyle Titanium Plus Diesel BSIV',
       'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV'], dtype=object)

In [4]:
car_data["mileage"].unique()

array(['23.4 kmpl', '21.14 kmpl', '17.7 kmpl', '23.0 kmpl', '16.1 kmpl',
       '20.14 kmpl', '17.3 km/kg', '23.59 kmpl', '20.0 kmpl',
       '19.01 kmpl', '17.3 kmpl', '19.3 kmpl', nan, '18.9 kmpl',
       '18.15 kmpl', '24.52 kmpl', '19.7 kmpl', '22.54 kmpl', '21.0 kmpl',
       '25.5 kmpl', '26.59 kmpl', '21.5 kmpl', '20.3 kmpl', '21.4 kmpl',
       '24.7 kmpl', '18.2 kmpl', '16.8 kmpl', '24.3 kmpl', '14.0 kmpl',
       '18.6 kmpl', '33.44 km/kg', '23.95 kmpl', '17.0 kmpl',
       '20.63 kmpl', '13.93 kmpl', '16.0 kmpl', '17.8 kmpl', '18.5 kmpl',
       '12.55 kmpl', '12.99 kmpl', '14.8 kmpl', '13.5 kmpl', '26.0 kmpl',
       '20.65 kmpl', '27.3 kmpl', '11.36 kmpl', '17.68 kmpl',
       '14.28 kmpl', '18.53 kmpl', '14.84 kmpl', '21.12 kmpl',
       '20.36 kmpl', '21.27 kmpl', '18.16 kmpl', '22.0 kmpl', '25.1 kmpl',
       '20.51 kmpl', '21.66 kmpl', '25.2 kmpl', '22.9 kmpl', '16.02 kmpl',
       '20.54 kmpl', '22.77 kmpl', '15.71 kmpl', '23.1 kmpl',
       '19.02 kmpl', '19.81 kmpl'

In [5]:
car_data["engine"].unique()

array(['1248 CC', '1498 CC', '1497 CC', '1396 CC', '1298 CC', '1197 CC',
       '1061 CC', '796 CC', '1364 CC', '1399 CC', '1461 CC', '993 CC',
       nan, '1198 CC', '1199 CC', '998 CC', '1591 CC', '2179 CC',
       '1368 CC', '2982 CC', '2494 CC', '2143 CC', '2477 CC', '1462 CC',
       '2755 CC', '1968 CC', '1798 CC', '1196 CC', '1373 CC', '1598 CC',
       '1998 CC', '1086 CC', '1194 CC', '1172 CC', '1405 CC', '1582 CC',
       '999 CC', '2487 CC', '1999 CC', '3604 CC', '2987 CC', '1995 CC',
       '1451 CC', '1969 CC', '2967 CC', '2497 CC', '1797 CC', '1991 CC',
       '2362 CC', '1493 CC', '1599 CC', '1341 CC', '1794 CC', '799 CC',
       '1193 CC', '2696 CC', '1495 CC', '1186 CC', '1047 CC', '2498 CC',
       '2956 CC', '2523 CC', '1120 CC', '624 CC', '1496 CC', '1984 CC',
       '2354 CC', '814 CC', '793 CC', '1799 CC', '936 CC', '1956 CC',
       '1997 CC', '1499 CC', '1948 CC', '2997 CC', '2489 CC', '2499 CC',
       '2609 CC', '2953 CC', '1150 CC', '1994 CC', '1388 CC', '152

In [6]:
car_data["max_power"].unique()

array(['74 bhp', '103.52 bhp', '78 bhp', '90 bhp', '88.2 bhp',
       '81.86 bhp', '57.5 bhp', '37 bhp', '67.1 bhp', '68.1 bhp',
       '108.45 bhp', '60 bhp', '73.9 bhp', nan, '67 bhp', '82 bhp',
       '88.5 bhp', '46.3 bhp', '88.73 bhp', '64.1 bhp', '98.6 bhp',
       '88.8 bhp', '83.81 bhp', '83.1 bhp', '47.3 bhp', '73.8 bhp',
       '34.2 bhp', '35 bhp', '81.83 bhp', '40.3 bhp', '121.3 bhp',
       '138.03 bhp', '160.77 bhp', '117.3 bhp', '116.3 bhp', '83.14 bhp',
       '67.05 bhp', '168.5 bhp', '100 bhp', '120.7 bhp', '98.63 bhp',
       '175.56 bhp', '103.25 bhp', '171.5 bhp', '100.6 bhp', '174.33 bhp',
       '187.74 bhp', '170 bhp', '78.9 bhp', '88.76 bhp', '86.8 bhp',
       '108.495 bhp', '108.62 bhp', '93.7 bhp', '103.6 bhp', '98.59 bhp',
       '189 bhp', '67.04 bhp', '68.05 bhp', '58.2 bhp', '82.85 bhp',
       '81.80 bhp', '73 bhp', '120 bhp', '94.68 bhp', '160 bhp', '65 bhp',
       '155 bhp', '69.01 bhp', '126.32 bhp', '138.1 bhp', '83.8 bhp',
       '126.2 bhp', '98.

In [7]:
car_data.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

## quality needed
- only 3 char is needed in name rest one will remove
- drop mileage column 
- split the value in engine and convert object into int
- drop max power and torque column
- remove all the nan value
- remove outliers if any
- convert float value of seat into int
- in outliers seats value is 14 and remove those vale which is above 9

In [8]:
car_data["name"] = car_data['name'].str.split(" ").str.slice(0,3).str.join(" ")

In [9]:
car_data.head()

name  year  selling_price  km_driven    fuel seller_type  \
0    Maruti Swift Dzire  2014         450000     145500  Diesel  Individual   
1       Skoda Rapid 1.5  2014         370000     120000  Diesel  Individual   
2  Honda City 2017-2020  2006         158000     140000  Petrol  Individual   
3    Hyundai i20 Sportz  2010         225000     127000  Diesel  Individual   
4      Maruti Swift VXI  2007         130000     120000  Petrol  Individual   

  transmission         owner     mileage   engine   max_power  \
0       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   
2       Manual   Third Owner   17.7 kmpl  1497 CC      78 bhp   
3       Manual   First Owner   23.0 kmpl  1396 CC      90 bhp   
4       Manual   First Owner   16.1 kmpl  1298 CC    88.2 bhp   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [10]:
car_data.drop(["mileage"], axis = 1 , inplace = True)

In [11]:
car_data.drop(["max_power", "torque"] ,axis = 1 , inplace = True)

In [12]:
car_data.head(10)

name  year  selling_price  km_driven    fuel seller_type  \
0    Maruti Swift Dzire  2014         450000     145500  Diesel  Individual   
1       Skoda Rapid 1.5  2014         370000     120000  Diesel  Individual   
2  Honda City 2017-2020  2006         158000     140000  Petrol  Individual   
3    Hyundai i20 Sportz  2010         225000     127000  Diesel  Individual   
4      Maruti Swift VXI  2007         130000     120000  Petrol  Individual   
5     Hyundai Xcent 1.2  2017         440000      45000  Petrol  Individual   
6        Maruti Wagon R  2007          96000     175000     LPG  Individual   
7         Maruti 800 DX  2001          45000       5000  Petrol  Individual   
8      Toyota Etios VXD  2011         350000      90000  Diesel  Individual   
9      Ford Figo Diesel  2013         200000     169000  Diesel  Individual   

  transmission         owner   engine  seats  
0       Manual   First Owner  1248 CC    5.0  
1       Manual  Second Owner  1498 CC    5.0  
2       Manual   Third Owner  1497 CC    5.0  
3       Manual   First Owner  1396 CC    5.0  
4       Manual   First Owner  1298 CC    5.0  
5       Manual   First Owner  1197 CC    5.0  
6       Manual   First Owner  1061 CC    5.0  
7       Manual  Second Owner   796 CC    4.0  
8       Manual   First Owner  1364 CC    5.0  
9       Manual   First Owner  1399 CC    5.0

In [13]:
car_data.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
engine           221
seats            221
dtype: int64

In [14]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           8128 non-null   object 
 1   year           8128 non-null   int64  
 2   selling_price  8128 non-null   int64  
 3   km_driven      8128 non-null   int64  
 4   fuel           8128 non-null   object 
 5   seller_type    8128 non-null   object 
 6   transmission   8128 non-null   object 
 7   owner          8128 non-null   object 
 8   engine         7907 non-null   object 
 9   seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(6)
memory usage: 635.1+ KB


In [15]:
car_data["engine"].value_counts()

1248 CC    1017
1197 CC     832
998 CC      453
796 CC      444
2179 CC     389
           ... 
3498 CC       1
2835 CC       1
2197 CC       1
2446 CC       1
1339 CC       1
Name: engine, Length: 121, dtype: int64

In [16]:
car_data["engine"]= car_data['engine'].fillna("1248 cc")

In [17]:
car_data["engine"] = car_data["engine"].str.split(" ").str.get(0).astype(int)

In [18]:
car_data.head()

name  year  selling_price  km_driven    fuel seller_type  \
0    Maruti Swift Dzire  2014         450000     145500  Diesel  Individual   
1       Skoda Rapid 1.5  2014         370000     120000  Diesel  Individual   
2  Honda City 2017-2020  2006         158000     140000  Petrol  Individual   
3    Hyundai i20 Sportz  2010         225000     127000  Diesel  Individual   
4      Maruti Swift VXI  2007         130000     120000  Petrol  Individual   

  transmission         owner  engine  seats  
0       Manual   First Owner    1248    5.0  
1       Manual  Second Owner    1498    5.0  
2       Manual   Third Owner    1497    5.0  
3       Manual   First Owner    1396    5.0  
4       Manual   First Owner    1298    5.0

In [19]:
car_data["seats"] = car_data["seats"].fillna("5.0")

In [20]:
car_data.head(20)

name  year  selling_price  km_driven    fuel seller_type  \
0      Maruti Swift Dzire  2014         450000     145500  Diesel  Individual   
1         Skoda Rapid 1.5  2014         370000     120000  Diesel  Individual   
2    Honda City 2017-2020  2006         158000     140000  Petrol  Individual   
3      Hyundai i20 Sportz  2010         225000     127000  Diesel  Individual   
4        Maruti Swift VXI  2007         130000     120000  Petrol  Individual   
5       Hyundai Xcent 1.2  2017         440000      45000  Petrol  Individual   
6          Maruti Wagon R  2007          96000     175000     LPG  Individual   
7           Maruti 800 DX  2001          45000       5000  Petrol  Individual   
8        Toyota Etios VXD  2011         350000      90000  Diesel  Individual   
9        Ford Figo Diesel  2013         200000     169000  Diesel  Individual   
10   Renault Duster 110PS  2014         500000      68000  Diesel  Individual   
11          Maruti Zen LX  2005          92000     100000  Petrol  Individual   
12     Maruti Swift Dzire  2009         280000     140000  Diesel  Individual   
13       Maruti Swift 1.3  2007         200000      80000  Petrol  Individual   
14         Maruti Wagon R  2009         180000      90000  Petrol  Individual   
15       Mahindra KUV 100  2016         400000      40000  Petrol  Individual   
16     Maruti Ertiga SHVS  2016         778000      70000  Diesel  Individual   
17        Hyundai i20 1.4  2012         500000      53000  Diesel  Individual   
18         Maruti Alto LX  2002         150000      80000  Petrol  Individual   
19  Hyundai i20 2015-2017  2016         680000     100000  Diesel  Individual   

   transmission         owner  engine seats  
0        Manual   First Owner    1248     5  
1        Manual  Second Owner    1498     5  
2        Manual   Third Owner    1497     5  
3        Manual   First Owner    1396     5  
4        Manual   First Owner    1298     5  
5        Manual   First Owner    1197     5  
6        Manual   First Owner    1061     5  
7        Manual  Second Owner     796     4  
8        Manual   First Owner    1364     5  
9        Manual   First Owner    1399     5  
10       Manual  Second Owner    1461     5  
11       Manual  Second Owner     993     5  
12       Manual  Second Owner    1248     5  
13       Manual  Second Owner    1248   5.0  
14       Manual  Second Owner    1061     5  
15       Manual   First Owner    1198     5  
16       Manual  Second Owner    1248     7  
17       Manual  Second Owner    1396     5  
18       Manual  Second Owner     796     5  
19       Manual   First Owner    1396     5

In [21]:
car_data["seats"].unique()

array([5.0, 4.0, '5.0', 7.0, 8.0, 6.0, 9.0, 10.0, 14.0, 2.0], dtype=object)

In [22]:
car_data["seats"].isnull().sum()

0

In [23]:
car_data["seats"] = car_data["seats"].astype(float)

In [24]:
car_data['seats'].unique()

array([ 5.,  4.,  7.,  8.,  6.,  9., 10., 14.,  2.])

In [25]:
car_data["seats"] = car_data["seats"].astype(int)

In [26]:
car_data = car_data[car_data["seats"]<9]

In [27]:
car_data["seats"].unique()

array([5, 4, 7, 8, 6, 2])

In [28]:
car_data["seats"].isnull().sum()

0

In [29]:
car_data["seats"]

0       5
1       5
2       5
3       5
4       5
       ..
8123    5
8124    5
8125    5
8126    5
8127    5
Name: seats, Length: 8028, dtype: int32

In [30]:
car_data.head(20)

name  year  selling_price  km_driven    fuel seller_type  \
0      Maruti Swift Dzire  2014         450000     145500  Diesel  Individual   
1         Skoda Rapid 1.5  2014         370000     120000  Diesel  Individual   
2    Honda City 2017-2020  2006         158000     140000  Petrol  Individual   
3      Hyundai i20 Sportz  2010         225000     127000  Diesel  Individual   
4        Maruti Swift VXI  2007         130000     120000  Petrol  Individual   
5       Hyundai Xcent 1.2  2017         440000      45000  Petrol  Individual   
6          Maruti Wagon R  2007          96000     175000     LPG  Individual   
7           Maruti 800 DX  2001          45000       5000  Petrol  Individual   
8        Toyota Etios VXD  2011         350000      90000  Diesel  Individual   
9        Ford Figo Diesel  2013         200000     169000  Diesel  Individual   
10   Renault Duster 110PS  2014         500000      68000  Diesel  Individual   
11          Maruti Zen LX  2005          92000     100000  Petrol  Individual   
12     Maruti Swift Dzire  2009         280000     140000  Diesel  Individual   
13       Maruti Swift 1.3  2007         200000      80000  Petrol  Individual   
14         Maruti Wagon R  2009         180000      90000  Petrol  Individual   
15       Mahindra KUV 100  2016         400000      40000  Petrol  Individual   
16     Maruti Ertiga SHVS  2016         778000      70000  Diesel  Individual   
17        Hyundai i20 1.4  2012         500000      53000  Diesel  Individual   
18         Maruti Alto LX  2002         150000      80000  Petrol  Individual   
19  Hyundai i20 2015-2017  2016         680000     100000  Diesel  Individual   

   transmission         owner  engine  seats  
0        Manual   First Owner    1248      5  
1        Manual  Second Owner    1498      5  
2        Manual   Third Owner    1497      5  
3        Manual   First Owner    1396      5  
4        Manual   First Owner    1298      5  
5        Manual   First Owner    1197      5  
6        Manual   First Owner    1061      5  
7        Manual  Second Owner     796      4  
8        Manual   First Owner    1364      5  
9        Manual   First Owner    1399      5  
10       Manual  Second Owner    1461      5  
11       Manual  Second Owner     993      5  
12       Manual  Second Owner    1248      5  
13       Manual  Second Owner    1248      5  
14       Manual  Second Owner    1061      5  
15       Manual   First Owner    1198      5  
16       Manual  Second Owner    1248      7  
17       Manual  Second Owner    1396      5  
18       Manual  Second Owner     796      5  
19       Manual   First Owner    1396      5

In [31]:
car_data.shape

(8028, 10)

In [32]:
car_data.describe()

year  selling_price     km_driven       engine        seats
count  8028.000000   8.028000e+03  8.028000e+03  8028.000000  8028.000000
mean   2013.817015   6.403954e+05  6.927684e+04  1441.016941     5.357623
std       4.049651   8.107670e+05  5.629823e+04   489.057225     0.849322
min    1983.000000   2.999900e+04  1.000000e+00   624.000000     2.000000
25%    2011.000000   2.509990e+05  3.500000e+04  1197.000000     5.000000
50%    2015.000000   4.500000e+05  6.000000e+04  1248.000000     5.000000
75%    2017.000000   6.800000e+05  9.527500e+04  1498.000000     5.000000
max    2020.000000   1.000000e+07  2.360457e+06  3604.000000     8.000000

In [33]:
car_data[car_data['selling_price']>6e6]

name  year  selling_price  km_driven    fuel seller_type  \
170   Volvo XC90 T8  2017       10000000      30000  Petrol  Individual   
2938  BMW X7 xDrive  2020        7200000       5000  Diesel  Individual   
4950     Audi A6 35  2019        6223000       7800  Petrol      Dealer   
4952     Audi A6 35  2019        6523000      23600  Petrol      Dealer   

     transmission           owner  engine  seats  
170     Automatic     First Owner    1969      4  
2938    Automatic     First Owner    2993      7  
4950    Automatic  Test Drive Car    1798      5  
4952    Automatic  Test Drive Car    1798      5

In [34]:
car_data.to_csv("cleaned car data.csv")

## train our model

In [35]:
x = car_data.drop(["selling_price"],axis= 1)
y = car_data["selling_price"]

In [36]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size = 0.3)

In [37]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [38]:
ohe = OneHotEncoder()
ohe.fit(x[['name', "fuel","seller_type","transmission","owner"]])

OneHotEncoder()

In [39]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name', "fuel","seller_type","transmission","owner"]),remainder = "passthrough")

In [40]:
lr = LinearRegression()

In [41]:
pipe = make_pipeline(column_trans, lr)

In [42]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Ambassador CLASSIC 1500', 'Ambassador Classic 2000',
       'Ambassador Grand 1500', 'Ambassador Grand 2000',
       'Ashok Leyland Stile', 'Audi A3 35', 'Audi A3 40', 'Audi A4 1.8',
       'Audi A4 2.0', 'Audi A4 35', 'Audi A6 2.0', 'Audi A6 35',
       'Audi Q3 2.0', 'Au...
                                                                            array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object),
                                                                            array(['Dealer', 'Individual', 'Trustmark Dealer'], dtype=object),
                                                                            array(['Automatic', 'Manual'], dtype=object),
                                                                            

In [43]:
y_pred = pipe.predict(x_test)

In [44]:
y_pred

array([634266.99579281, 496993.69938369, 229713.65865052, ...,
       854772.18422726, 331479.94893701, 508551.47115842])

In [45]:
r2_score(y_test, y_pred)

0.9242279047150237

## select random state which is stable and where r2 score is more

In [46]:
score=[]
for i in range(100):
    x_train, x_test, y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans, lr)
    pipe.fit(x_train, y_train)
    y_pred= pipe.predict(x_test)
    score.append(r2_score(y_test,y_pred))
# print(r2_score(y_test, y_pred),i)
    

In [47]:
np.argmax(score)

23

In [48]:
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 23)
lr = LinearRegression()
pipe = make_pipeline(column_trans, lr)
pipe.fit(x_train, y_train)
y_pred= pipe.predict(x_test)
r2_score(y_test,y_pred)

0.9664674667745705

In [49]:
import pickle

In [50]:
pickle.dump(pipe,open("linearregcarmodel.sav", "wb"))

In [51]:
loaded_model = pickle.load(open("linearregcarmodel.sav", "rb"))
loaded_model

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Ambassador CLASSIC 1500', 'Ambassador Classic 2000',
       'Ambassador Grand 1500', 'Ambassador Grand 2000',
       'Ashok Leyland Stile', 'Audi A3 35', 'Audi A3 40', 'Audi A4 1.8',
       'Audi A4 2.0', 'Audi A4 35', 'Audi A6 2.0', 'Audi A6 35',
       'Audi Q3 2.0', 'Au...
                                                                            array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object),
                                                                            array(['Dealer', 'Individual', 'Trustmark Dealer'], dtype=object),
                                                                            array(['Automatic', 'Manual'], dtype=object),
                                                                            

In [52]:
pipe.predict(pd.DataFrame([["Skoda Rapid 1.5",2019, 220000, "Petrol","Individual","Manual","Second Owner",1498,5]],columns=["name", "year","km_driven","fuel","seller_type","transmission","owner","engine","seats"]))

array([696675.77310458])